language: objective-c
cache: cocoapods
osx_image: xcode9
notification:
    email: 
    - tungnguyenlee2t@gmail.com
before_instal:
    - sudo gem uninstall bundler
    - gem install bundler
    - rbenv rehash
    - gem install bundler --pre 
    - bundle install
    - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
    - bunble exec pod install
    - brew update
    - brew outdated carthage || brew upgrade carthage
script:
    - xcodebuild test -workspace jlpt-ios-release.xcworkspace -scheme jlpt-ios-release  -destination "platform=iOS Simulator,name=iPhone 7,OS=11.0" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet

